version: '3'
  
services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    links:
       - redis:redis
    command: python /code/manage.py runserver 0.0.0.0:8000
  nginx:
     build: ./nginx/
     ports:
       - 80:80
  redis:
    image: redis:latest
    expose:
      - 6379
