language: python
os: linux

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
    - python -V
    - coverage run --source=. manage.py watch.test
   # - pylint --load-plugins pylint_django --disable=missing-docstring ./watch
   # - pylint --load-plugins pylint_django --disable=missing-docstring ./whattowatch

after_success:
  coveralls
