language: python
os: linux

script:
    - python -V
   # - pylint --load-plugins pylint_django --disable=missing-docstring ./watch
   #  - pylint --load-plugins pylint_django --disable=missing-docstring ./whattowatch
service_name: travis-pro
repo_token: hADMbgdu4bx8M0DQjASXBlnfVHUJGuu0n
