language: python
os: linux
image: docker:latest
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
services:
- docker:dind

script:
    - pylint --load-plugins pylint_django --disable=missing-docstring ./watch
