version: '3'
  
services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    links:
       - redis:redis
    command: python /code/manage.py runserver 0.0.0.0:8000

  nginx:
     build: ./nginx/
     depends on:
       - web
     ports:
       - 80:80
     links:
       - web:web

  redis:
    image: redis:latest
    expose:
      - 6379
